release:
    name: Release to Github, GitHub Packages, NPM
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      issues: write
      pull-requests: write
    if: >
      github.actor != 'semantic-release-bot'
      && ! contains(github.event.head_commit.message, 'chore(release):')
    steps:
      - name: ♻️ Environment
        run: |
          echo IS_PRIVATE: ${{ env.IS_PRIVATE }}

      - name: 🐳 Start MongoDB Replica Set
        run: |
          docker run -d \
            --name mongodb-rs \
            -p 27017:27017 \
            -e MONGO_INITDB_ROOT_USERNAME=root \
            -e MONGO_INITDB_ROOT_PASSWORD=password \
            mongo:7.0 \
            --replSet rs0 --bind_ip_all

          # Wait for MongoDB to be ready
          sleep 5

          # Initialize replica set
          docker exec mongodb-rs mongosh --eval "
            rs.initiate({
              _id: 'rs0',
              members: [{ _id: 0, host: 'localhost:27017' }]
            })
          "

          # Wait for replica set to be ready
          sleep 5

      - name: ⤵️ Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ⚙️ [public]Setup Node
        if: ${{ env.IS_PRIVATE != 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://registry.npmjs.org'
          scope: ${{ env.USERNAME }}

      - name: ⚙️ [private]Setup Node
        if: ${{ env.IS_PRIVATE == 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://npm.pkg.github.com/'

      - name: 🚧 Install dependencies
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ env.EVEBLE_TYPES_AUTH_TOKEN }}

      - name: ✅ Test
        run: yarn test
        env:
          MONGO_URI: mongodb://root:password@localhost:27017/?replicaSet=rs0&authSource=admin

      - name: 🗝️ Build
        run: yarn build

      - name: 🚀 [public]Release
        if: ${{ env.IS_PRIVATE != 'true' }}
        uses: cycjimmy/semantic-release-action@v3
        id: public-semantic
        with:
          semantic_version: ${{env.SEMANTIC_VERSION}}
          dry_run: false
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            @semantic-release/npm@9.0.2
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 🚀 [private]Release
        if: ${{ env.IS_PRIVATE == 'true' }}
        uses: cycjimmy/semantic-release-action@v3
        id: private-semantic
        with:
          semantic_version: ${{env.SEMANTIC_VERSION}}
          dry_run: false
          extra_plugins: |
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            @semantic-release/npm@9.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🎉 Output release
        if: steps.semantic.outputs.new_release_published == 'true'
        run: |
          echo ${{ steps.semantic.outputs.new_release_version }}
          echo @${{ env.USERNAME }}

      - name: 🔀 Setup Node with GitHub Package Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}.x
          registry-url: 'https://npm.pkg.github.com'
          scope: ${{ env.USERNAME }}
          always-auth: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ env.GITHUB_TOKEN }}

      - name: 🎉 Publish To GitHub Package Registry
        if: steps.semantic.outputs.new_release_published == 'true'
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🚧 Install dependencies on Docusaurus
        run: |
          cd ./website
          yarn install

      - name: 📄 Build docs
        run: yarn docs:build

      - name: Fix 404 Page not found for Github in case .nojekyll is missing in ./website/static
        run: touch ./website/build/.nojekyll

      - name: 🤔 Deploy documentation to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/build
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
