name: 'Update tracked Pull Request'

on:
  pull_request:
    types: [opened]

jobs:
  format:
    name: Format tracked Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Initialize workflow variables
        id: vars
        shell: bash
        run: |
          PROJECT_KEY=$PROJECT_KEY
          echo ::set-output name=PROJECT_KEY::${PROJECT_KEY}
          unset HAS_PROJECT_KEY
          if [ -n $PROJECT_KEY ]; then HAS_PROJECT_KEY='true' ; fi
          echo set-output name=HAS_PROJECT_KEY::${HAS_PROJECT_KEY}
          echo ::set-output name=HAS_PROJECT_KEY::${HAS_PROJECT_KEY}
        env:
          PROJECT_KEY: '${{ secrets.PROJECT_KEY }}'
      - name: Update Pull Request
        if: ${{ steps.vars.outputs.HAS_PROJECT_KEY && contains(github.event.pull_request.title, steps.vars.outputs.PROJECT_KEY ) }}
        uses: tzkhan/pr-update-action@v1.1.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-regex: ${{ secrets.PROJECT_KEY_PATTERN }} # [a-zA-Z0-9_]{3}-[\d]+
          lowercase-branch: true
          title-template: '[%branch%]'
          replace-title: false
          title-prefix-space: true
          uppercase-title: false
          body-template: |
            [Link to %branch%](${{ secrets.TICKET_URL }}%branch%)
            ---
          replace-body: false
          body-prefix-newline-count: 2
          uppercase-body: true
